### PR TITLE
fix sed for windows

### PR DESCRIPTION
**Pull request by en-GB**

### CODE REVIEW

**Review by se-jaeger — CHANGES_REQUESTED** [review]
Are you sure this works for Windows? On macOS it creates another file `Chart.yamle`. We should detected the OS within the makefile and use the appropriate command.

**Review by se-jaeger — COMMENTED** [review]
Your suggestion did not work on macOS since `--in-place=''`  is not available.

What do you think about mine proposal. Here we would use specific command depending on OS. Could you test this? It should replace versions, e.g., `0.1.8` to `0.1.9` in the `pyproject.toml` and other files.

**Comment by en-GB** [comment]
Apparently the problem is that macOS uses bsd sed by default while pretty much everyone else uses gnu sed.
Since not all windows shells set $OS to windows_nt i changed it to assume GNU sed everywhere except on macOS.
This is probably good enough but maybe it would be better to grep on sed --version

Alternatively we could set it to always make a new file and then delete it afterwards, which should be portable.

**Review by se-jaeger — APPROVED** [review]
You're right! - Then it's definitively better to treat macOS  as the special case.

**Pull request merged**
